### ISSUE TITLE
Follow-up: specs_e2e/rails_8 cannot boot in RAILS_ENV=production (solid_queue not in its Gemfile)

### ISSUE THREAD

**Issue by justin808** [shakacode/cypress-playwright-on-rails#256]
Source: found by the QA lane for PR #253 (wave 1 of the 2026-09-03 release batch); pre-existing and unrelated to that PR.

## Problem

`specs_e2e/rails_8/config/environments/production.rb:54` sets `config.solid_queue.connects_to`, but the example app's Gemfile does not include `solid_queue` (or `solid_cache`). Booting the app in production fails immediately:

```
undefined method 'solid_queue' for an instance of Rails::Application::Configuration
```

CI never boots the example app in production, so this went unnoticed. It matters now because the production-default behaviour introduced by #13/#253 (`use_middleware` resolves to disabled in production) cannot be demonstrated against the repo's own example app; QA had to use a minimal scratch Rails 8 app instead.

## Proposed fix

Either add `solid_queue` and `solid_cache` to `specs_e2e/rails_8/Gemfile` (they are Rails 8 defaults), or remove the `config.solid_queue.connects_to` / `config.cache_store = :solid_cache_store` lines from `production.rb` since the example app only ever runs in test. Removing the lines is the smaller change.

## Acceptance

`cd specs_e2e/rails_8 && RAILS_ENV=production SECRET_KEY_BASE=x bundle exec bin/rails middleware` boots and lists the stack; `CypressOnRails::Middleware` is absent in production with the generated initializer and present in test.
